# Generated by Django 4.2.7 on 2024-02-13 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(help_text="内容", verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="作者",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="标签名称",
                        max_length=200,
                        unique=True,
                        verbose_name="标签名称",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(help_text="内容", verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="标题", max_length=200, verbose_name="标题"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("a", "已解决"), ("n", "未开始"), ("i", "正在进行")],
                        default="n",
                        help_text="状态",
                        max_length=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="作者",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="标签",
                        to="fuzhuxian.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="图片", upload_to="media/", verbose_name="图片"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="对应帖子或评论",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fuzhuxian.comment",
                        verbose_name="对应帖子或评论",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        help_text="对应帖子或评论",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fuzhuxian.post",
                        verbose_name="对应帖子或评论",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                help_text="帖子外键",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="fuzhuxian.post",
                verbose_name="帖子外键",
            ),
        ),
    ]
