# Generated by Django 3.2.24 on 2024-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzhuxian', '0002_auto_20240216_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='图片', upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('n', '未开始'), ('i', '正在进行'), ('a', '已解决')], default='n', help_text='状态', max_length=1, verbose_name='状态'),
        ),
    ]
